# .streamlit/secrets.toml  (placeholders only — safe to commit)
SHEET_ID = "YOUR_GOOGLE_SHEET_ID"
SLEEPER_LEAGUE_ID = "YOUR_SLEEPER_LEAGUE_ID"

# For local testing only — leave empty in GitHub.
# On Streamlit Cloud, set real secrets in the app's "Edit secrets" UI.
# GOOGLE_SERVICE_ACCOUNT_JSON = "{ ... }"
